# Generated by Django 4.2.23 on 2025-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quote_text', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('watches', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
    ]
