# Generated by Django 4.2.23 on 2025-08-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='source_type',
            field=models.CharField(choices=[('Ф', 'Фильм'), ('К', 'Книга'), ('С', 'Сериал'), ('Ч', 'Известный человек')], default='Ч', max_length=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
