# Generated by Django 4.2.23 on 2025-08-26 11:43

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('random_quote', '0002_quote_source_type_alter_quote_quote_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-likes', '-weight', '-watches']},
        ),
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.TextField(help_text='Текст цитаты (минимум 10 символов)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(help_text='Источник цитаты (минимум 2 символа)', max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source_type',
            field=models.CharField(choices=[('Ф', 'Фильм'), ('К', 'Книга'), ('С', 'Сериал'), ('Ч', 'Известный человек')], default='Ч', help_text='Тип источника цитаты', max_length=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='watches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.IntegerField(default=1, help_text='Вес цитаты (влияет на частоту показа)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['weight'], name='random_quot_weight_48c63d_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['likes'], name='random_quot_likes_2ec293_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['source'], name='random_quot_source_fb7bc2_idx'),
        ),
    ]
